CC = g++

CFLAGS = -lallegro -lallegro_image -lallegro_font -lallegro_ttf -lallegro_audio -lallegro_acodec -std=c++14

TARGET = LodeRunner

all: $(TARGET)

$(TARGET) : *.cpp
	 	$(CC) -o $(TARGET) *.cpp $(CFLAGS)
